export interface LentenDay {
  day: number;
  title: string;
  scripture: string;
  prayer: string;
  fast?: string;
  almsgiving?: string;
  reflection: string;
  type: "fast" | "pray" | "give" | "reflect";
}

export const LENTEN_DAYS: LentenDay[] = [
  { day: 1,  type: "fast",    title: "Ash Wednesday",           scripture: "Joel 2:12",        prayer: "Create in me a clean heart, O God.",                        fast: "Fast and abstain from meat today.",                          almsgiving: "Donate to a local food bank.",             reflection: "Return to me with your whole heart. Begin Lent with a sincere act of repentance." },
  { day: 2,  type: "pray",    title: "Begin with Prayer",        scripture: "Matthew 6:6",      prayer: "Lord, teach me to pray in secret.",                          reflection: "Enter your inner room and pray to your Father in secret." },
  { day: 3,  type: "reflect", title: "The Desert",               scripture: "Matthew 4:1-2",    prayer: "Lead me through my desert, Lord.",                           reflection: "Jesus fasted 40 days. What attachments can you fast from this Lent?" },
  { day: 4,  type: "give",    title: "Almsgiving",               scripture: "Luke 12:33",        prayer: "Lord, loosen my grip on earthly things.",                   almsgiving: "Give something you value to someone in need.",          reflection: "Where your treasure is, there your heart will be also." },
  { day: 5,  type: "fast",    title: "Fasting from Distraction", scripture: "Psalm 46:10",       prayer: "Be still and know that I am God.",                           fast: "Fast from your phone for one hour today.",                   reflection: "Silence is the language God speaks. Create space for Him." },
  { day: 6,  type: "pray",    title: "The Our Father",           scripture: "Matthew 6:9-13",   prayer: "Our Father, who art in Heaven...",                           reflection: "Pray the Our Father slowly today — one phrase at a time." },
  { day: 7,  type: "reflect", title: "First Sunday of Lent",     scripture: "Matthew 4:1-11",   prayer: "Lord, strengthen me against temptation.",                    reflection: "Jesus was tempted in every way as we are, yet without sin. Bring your temptations to Him." },
  { day: 8,  type: "give",    title: "Visiting the Lonely",      scripture: "Matthew 25:36",    prayer: "Lord, show me who needs my company today.",                  almsgiving: "Visit or call an elderly or isolated person.",          reflection: "I was lonely and you visited me. Who in your life needs a visit?" },
  { day: 9,  type: "fast",    title: "Fasting from Complaint",   scripture: "Philippians 4:11", prayer: "I have learned to be content in all things.",                 fast: "Go the whole day without complaining.",                      reflection: "Contentment is a discipline. Offer your frustrations to God." },
  { day: 10, type: "pray",    title: "The Rosary",               scripture: "Luke 1:28",        prayer: "Hail Mary, full of grace...",                                reflection: "Pray a decade of the Rosary meditating on the Sorrowful Mysteries." },
  { day: 11, type: "reflect", title: "Repentance",               scripture: "Luke 15:18",       prayer: "Father, I have sinned against heaven and against you.",      reflection: "The Prodigal Son rose and returned. Is God calling you to confession this Lent?" },
  { day: 12, type: "give",    title: "Tithing Your Time",        scripture: "Ecclesiastes 3:1", prayer: "Lord, help me use my time for Your glory.",                  almsgiving: "Volunteer one hour at a parish or charity today.",       reflection: "Time is our most valuable resource. Give some of it to God and neighbor." },
  { day: 13, type: "fast",    title: "Fasting from Gossip",      scripture: "James 3:5",        prayer: "Set a guard, Lord, over my mouth.",                          fast: "Speak no negative words about another person today.",        reflection: "The tongue is a small flame that can set a great forest ablaze." },
  { day: 14, type: "pray",    title: "Lectio Divina",            scripture: "Hebrews 4:12",     prayer: "Speak, Lord, your servant is listening.",                    reflection: "Open the Bible to today's Mass readings and practice Lectio Divina." },
  { day: 15, type: "reflect", title: "Second Sunday of Lent",    scripture: "Matthew 17:5",     prayer: "This is my beloved Son — listen to Him.",                   reflection: "On the mountain, God says: listen. What is Jesus saying to you this Lent?" },
  { day: 16, type: "give",    title: "Random Act of Charity",    scripture: "Matthew 5:42",     prayer: "Lord, make me generous without expectation.",                almsgiving: "Perform an anonymous act of kindness for a stranger.",  reflection: "Give to those who ask. Do it secretly. Let God see." },
  { day: 17, type: "fast",    title: "Fasting from Comfort",     scripture: "Romans 8:18",      prayer: "The sufferings of this time are nothing to the glory ahead.", fast: "Skip a comfort — dessert, streaming, a hot shower.",         reflection: "Small mortifications train the will and unite us to the Cross." },
  { day: 18, type: "pray",    title: "Examination of Conscience",scripture: "Psalm 139:23",     prayer: "Search me, God, and know my heart.",                         reflection: "Spend 10 minutes in quiet examination. Prepare for confession." },
  { day: 19, type: "reflect", title: "Go to Confession",         scripture: "John 20:23",       prayer: "Lord, I am heartily sorry for having offended You.",          reflection: "Make time for the Sacrament of Reconciliation this week. Christ is waiting." },
  { day: 20, type: "give",    title: "Forgive Someone",          scripture: "Matthew 6:14",     prayer: "Forgive us our trespasses as we forgive those who trespass.", almsgiving: "Extend forgiveness to someone who has hurt you.",       reflection: "Unforgiveness is a prison. Christ's mercy sets us free — and others through us." },
  { day: 21, type: "fast",    title: "Fast from Anger",          scripture: "Ephesians 4:26",   prayer: "Lord, give me patience and a gentle spirit.",                 fast: "When you feel anger rise, pause and pray before responding.", reflection: "Be angry, but do not sin. Let not the sun go down on your anger." },
  { day: 22, type: "pray",    title: "Third Sunday of Lent",     scripture: "John 4:13-14",     prayer: "Lord, give me this living water.",                            reflection: "Jesus offers living water to the Samaritan woman — and to you. Come to the well." },
  { day: 23, type: "reflect", title: "The Cross",                scripture: "1 Corinthians 1:18",prayer: "May I never boast except in the Cross of Jesus Christ.",      reflection: "The Cross is foolishness to the perishing, but power to those who are saved." },
  { day: 24, type: "give",    title: "Pray for Enemies",         scripture: "Matthew 5:44",     prayer: "Lord, I pray for those who have hurt me.",                   almsgiving: "Name one person who has wronged you and pray for them.", reflection: "Love your enemies. Pray for those who persecute you. This is radical grace." },
  { day: 25, type: "fast",    title: "Technology Fast",          scripture: "Matthew 6:21",     prayer: "Where my treasure is, there my heart is.",                   fast: "Fast from social media completely today.",                   reflection: "Where is your attention? Whatever you scroll toward — that is what you treasure." },
  { day: 26, type: "pray",    title: "Divine Mercy Chaplet",     scripture: "Luke 18:13",       prayer: "O God, be merciful to me, a sinner.",                        reflection: "Pray the Divine Mercy Chaplet at 3 PM — the Hour of Mercy." },
  { day: 27, type: "reflect", title: "Stations of the Cross",    scripture: "Luke 23:26",       prayer: "We adore You, O Christ, and we bless You.",                  reflection: "Walk the Stations of the Cross today — at church or in prayer." },
  { day: 28, type: "give",    title: "Give to the Poor",         scripture: "Proverbs 19:17",   prayer: "Lord, let me see You in the face of the poor.",              almsgiving: "Give a meal, clothes, or money to someone in genuine need.", reflection: "Whoever is kind to the poor lends to the Lord." },
  { day: 29, type: "pray",    title: "Fourth Sunday of Lent",    scripture: "John 3:16",        prayer: "For God so loved the world that He gave His only Son.",       reflection: "Laetare Sunday — a Sunday of joy. God loved you so much He gave everything." },
  { day: 30, type: "fast",    title: "Fasting from Judgment",    scripture: "Matthew 7:1",      prayer: "Lord, remove the plank from my own eye.",                    fast: "Every time you judge someone today, say a Hail Mary instead.", reflection: "Do not judge, and you will not be judged. Mercy is the Lenten spirit." },
  { day: 31, type: "reflect", title: "Mary at the Cross",        scripture: "John 19:25",       prayer: "Holy Mother, pierce me with the sword of sorrow.",           reflection: "Mary stood at the foot of the Cross. Ask for her grace to stand firm in suffering." },
  { day: 32, type: "give",    title: "Write a Letter",           scripture: "Romans 16:1",      prayer: "Lord, let my words build others up.",                        almsgiving: "Write a letter of encouragement to someone struggling.",  reflection: "Words of kindness are a form of almsgiving. Who needs a word from you?" },
  { day: 33, type: "pray",    title: "Fifth Sunday of Lent",     scripture: "John 11:25",       prayer: "I am the resurrection and the life.",                        reflection: "Jesus wept at the tomb of Lazarus. He weeps with you in your suffering too." },
  { day: 34, type: "fast",    title: "A Full Day Fast",          scripture: "Isaiah 58:6",      prayer: "Is not this the fast I choose — to loose the bonds of wickedness?", fast: "Consider a full day fast from food with only water.",         reflection: "True fasting loosens chains, feeds the hungry, and brings us to God." },
  { day: 35, type: "reflect", title: "Palm Sunday",              scripture: "Matthew 21:9",     prayer: "Hosanna to the Son of David!",                              reflection: "The crowd shouts Hosanna today — and Crucify Him on Friday. Where is your heart?" },
  { day: 36, type: "pray",    title: "Holy Monday",              scripture: "John 12:3",        prayer: "Lord, may I pour myself out for You as Mary did.",           reflection: "Mary anointed Jesus with costly perfume. What costly thing will you offer Him?" },
  { day: 37, type: "reflect", title: "Holy Tuesday",             scripture: "John 13:21",       prayer: "Lord, is it I?",                                             reflection: "At the Last Supper, each disciple asks: is it I, Lord? Ask yourself honestly today." },
  { day: 38, type: "give",    title: "Holy Wednesday",           scripture: "Matthew 26:15",    prayer: "Lord, keep me from betraying You for any price.",            almsgiving: "Make a significant charitable donation before Easter.",  reflection: "Judas sold Jesus for 30 pieces of silver. What worldly thing tempts you to betray Christ?" },
  { day: 39, type: "pray",    title: "Holy Thursday",            scripture: "John 13:14",       prayer: "Lord, I want to serve as You served.",                       reflection: "Jesus washed His disciples' feet. Attend the Mass of the Lord's Supper tonight if possible." },
  { day: 40, type: "reflect", title: "Good Friday",              scripture: "John 19:30",       prayer: "It is finished.",                                            fast: "Fast and abstain from meat. Attend the Liturgy of the Lord's Passion.", reflection: "It is finished. Jesus gave everything. Spend time before the Cross in silence and gratitude." },
];