/**
 * Saint of the Day — keyed by MM-DD
 * Sources: Roman Martyrology, Catholic Calendar
 */

export interface Saint {
  name: string;
  feastDay: string; // MM-DD
  bio: string;
  patronOf?: string;
  bornDied?: string;
}

const SAINTS: Record<string, Saint> = {
  "01-01": {
    name: "Mary, Mother of God",
    feastDay: "01-01",
    bornDied: "1st century",
    bio: "On this Solemnity, the Church honors the Blessed Virgin Mary as the Mother of God (Theotokos). This title was formally defined at the Council of Ephesus in 431 AD. Mary's divine motherhood is the foundation of all her other privileges and her role in salvation history.",
    patronOf: "All Christians",
  },
  "01-02": {
    name: "Sts. Basil the Great & Gregory Nazianzen",
    feastDay: "01-02",
    bornDied: "329–379 / 329–390",
    bio: "Two of the three Cappadocian Fathers, both Doctors of the Church. Basil organized monastic life and defended the divinity of the Holy Spirit. Gregory's eloquent theology of the Trinity earned him the title 'The Theologian.'",
    patronOf: "Monks, theologians",
  },
  "01-03": {
    name: "The Most Holy Name of Jesus",
    feastDay: "01-03",
    bornDied: "–",
    bio: "This feast venerates the Holy Name of Jesus, at which 'every knee should bend' (Philippians 2:10). St. Bernardine of Siena popularized devotion to the Holy Name in the 15th century.",
  },
  "01-04": {
    name: "St. Elizabeth Ann Seton",
    feastDay: "01-04",
    bornDied: "1774–1821",
    bio: "First native-born American saint. A widow and mother of five, she converted to Catholicism and founded the Sisters of Charity — the first religious community established in the United States. She also opened the first Catholic school in America.",
    patronOf: "Catholic schools, widows, seafarers",
  },
  "01-05": {
    name: "St. John Neumann",
    feastDay: "01-05",
    bornDied: "1811–1860",
    bio: "Born in Bohemia, he immigrated to America and became the fourth Bishop of Philadelphia. He established hundreds of Catholic schools and was the first American bishop to be canonized.",
    patronOf: "Catholic education",
  },
  "01-06": {
    name: "St. André Bessette",
    feastDay: "01-06",
    bornDied: "1845–1937",
    bio: "A humble Holy Cross brother known as the 'Miracle Man of Montreal.' Despite having little education, he became famous for healings and built Saint Joseph's Oratory on Mount Royal, the largest church in Canada.",
    patronOf: "The sick, the poor",
  },
  "01-07": {
    name: "St. Raymond of Peñafort",
    feastDay: "01-07",
    bornDied: "1175–1275",
    bio: "Dominican priest and canonist who compiled the Decretals of Pope Gregory IX — the first official collection of Church law. He also persuaded St. Thomas Aquinas to write the Summa contra Gentiles.",
    patronOf: "Lawyers, canon lawyers",
  },
  "01-13": {
    name: "St. Hilary of Poitiers",
    feastDay: "01-13",
    bornDied: "315–368",
    bio: "Bishop of Poitiers and Doctor of the Church, called the 'Athanasius of the West.' He fought tirelessly against Arianism and wrote profound works on the Trinity.",
    patronOf: "Lawyers, children learning to walk",
  },
  "01-17": {
    name: "St. Anthony the Abbot",
    feastDay: "01-17",
    bornDied: "251–356",
    bio: "Father of Christian monasticism. At 20 he gave away his possessions and lived as a hermit in the Egyptian desert for decades. His life inspired thousands to pursue the monastic vocation.",
    patronOf: "Monks, animals, skin diseases",
  },
  "01-20": {
    name: "St. Sebastian",
    feastDay: "01-20",
    bornDied: "d. 288",
    bio: "Roman soldier and martyr who secretly aided persecuted Christians. When his faith was discovered, Emperor Diocletian ordered him shot with arrows. Miraculously surviving, he confronted the emperor again and was beaten to death.",
    patronOf: "Athletes, soldiers, archers",
  },
  "01-21": {
    name: "St. Agnes",
    feastDay: "01-21",
    bornDied: "291–304",
    bio: "A 12-year-old Roman girl who refused marriage and consecrated her virginity to Christ. She was martyred for her faith under Diocletian. Her name means 'pure' in Latin.",
    patronOf: "Girls, chastity, victims of sexual abuse",
  },
  "01-24": {
    name: "St. Francis de Sales",
    feastDay: "01-24",
    bornDied: "1567–1622",
    bio: "Bishop of Geneva and Doctor of the Church. He reconverted thousands in Chablais to Catholicism using gentle persuasion rather than force. His Introduction to the Devout Life showed ordinary people how to live holy lives.",
    patronOf: "Writers, journalists, the deaf",
  },
  "01-25": {
    name: "Conversion of St. Paul",
    feastDay: "01-25",
    bornDied: "d. ~67",
    bio: "This feast celebrates the dramatic conversion of Saul of Tarsus on the road to Damascus (Acts 9). From persecutor of Christians to Apostle to the Gentiles, Paul's transformation is one of the most remarkable in history.",
    patronOf: "Missionaries, evangelists",
  },
  "01-26": {
    name: "Sts. Timothy & Titus",
    feastDay: "01-26",
    bornDied: "1st century",
    bio: "Two disciples and co-workers of St. Paul. Timothy was the first Bishop of Ephesus; Titus was the first Bishop of Crete. Paul's letters to them (1 & 2 Timothy, Titus) are among the Pastoral Epistles of the New Testament.",
  },
  "01-28": {
    name: "St. Thomas Aquinas",
    feastDay: "01-28",
    bornDied: "1225–1274",
    bio: "Greatest theologian and philosopher of the Church, called the 'Angelic Doctor.' His Summa Theologiae remains one of the most influential works in Western thought. He united faith and reason in a brilliant synthesis.",
    patronOf: "Students, scholars, universities, theologians",
  },
  "02-02": {
    name: "Presentation of the Lord",
    feastDay: "02-02",
    bornDied: "–",
    bio: "Forty days after Christmas, the Church celebrates the Presentation of Jesus in the Temple (Luke 2:22-40). The prophet Simeon proclaimed Jesus the 'light of the Gentiles.' This feast is also called Candlemas — candles are blessed on this day.",
  },
  "02-03": {
    name: "St. Blaise",
    feastDay: "02-03",
    bornDied: "d. 316",
    bio: "Bishop and martyr. Legend holds that he miraculously healed a boy choking on a fishbone. On his feast day, the Church performs the Blessing of Throats — crossed candles are held to the throat as a sign of protection.",
    patronOf: "Throat ailments, wild animals",
  },
  "02-05": {
    name: "St. Agatha",
    feastDay: "02-05",
    bornDied: "d. 251",
    bio: "Young Sicilian virgin and martyr who refused the advances of a Roman official. She suffered terrible tortures and died in prison. One of seven women (besides Mary) commemorated by name in the Roman Canon of the Mass.",
    patronOf: "Breast cancer patients, nurses, Sicily",
  },
  "02-06": {
    name: "St. Paul Miki & Companions",
    feastDay: "02-06",
    bornDied: "d. 1597",
    bio: "Twenty-six martyrs crucified on a hill outside Nagasaki, Japan. Paul Miki, a Jesuit, preached from his cross as he died. The first canonized martyrs of the Far East.",
    patronOf: "Japan",
  },
  "02-10": {
    name: "St. Scholastica",
    feastDay: "02-10",
    bornDied: "480–547",
    bio: "Twin sister of St. Benedict and foundress of women's Benedictine monasticism. She met annually with her brother for spiritual conversation. She died three days after their last meeting, and Benedict saw her soul rise to Heaven as a dove.",
    patronOf: "Benedictine nuns, education",
  },
  "02-11": {
    name: "Our Lady of Lourdes",
    feastDay: "02-11",
    bornDied: "–",
    bio: "On this day in 1858, the Blessed Virgin Mary appeared to 14-year-old Bernadette Soubirous in a grotto at Lourdes, France. She identified herself as 'the Immaculate Conception.' Lourdes has since become the world's most visited Marian shrine, known for miraculous healings.",
    patronOf: "The sick, Lourdes",
  },
  "02-14": {
    name: "Sts. Cyril & Methodius",
    feastDay: "02-14",
    bornDied: "826–869 / 815–885",
    bio: "Brothers and missionaries to the Slavs, co-patrons of Europe. They created the Glagolitic alphabet to translate the Scriptures into Slavonic, making the Gospel accessible to the Slavic peoples.",
    patronOf: "Europe, Slavic peoples",
  },
  "02-22": {
    name: "Chair of St. Peter",
    feastDay: "02-22",
    bornDied: "–",
    bio: "This feast celebrates the authority of the papacy — the Chair (cathedra) symbolizes the teaching authority Christ gave to Peter (Matthew 16:18-19). It affirms the apostolic succession and the Pope's role as universal shepherd of the Church.",
  },
  "03-07": {
    name: "Sts. Perpetua & Felicity",
    feastDay: "03-07",
    bornDied: "d. 203",
    bio: "Carthaginian martyrs. Perpetua was a noblewoman and nursing mother; Felicity was her enslaved companion who gave birth in prison days before martyrdom. Their detailed prison diary is one of the earliest Christian documents written by a woman.",
    patronOf: "Mothers, expectant mothers, martyrs",
  },
  "03-17": {
    name: "St. Patrick",
    feastDay: "03-17",
    bornDied: "385–461",
    bio: "Apostle of Ireland. Kidnapped as a boy and enslaved in Ireland, he escaped, became a priest, and returned to evangelize his captors. His Confession and Letter to Coroticus are the earliest writings from Ireland. He used the shamrock to explain the Trinity.",
    patronOf: "Ireland, engineers, Nigeria",
  },
  "03-19": {
    name: "St. Joseph, Spouse of Mary",
    feastDay: "03-19",
    bornDied: "1st century",
    bio: "Foster father of Jesus and husband of the Blessed Virgin Mary. A just man who responded with faith and obedience to God's extraordinary call. Patron of the Universal Church since 1870. Pope Francis added him to all Eucharistic Prayers in 2013.",
    patronOf: "Universal Church, workers, fathers, families, a happy death",
  },
  "03-25": {
    name: "Annunciation of the Lord",
    feastDay: "03-25",
    bornDied: "–",
    bio: "The angel Gabriel announces to Mary that she will conceive the Son of God by the Holy Spirit. Mary's 'fiat' — 'Let it be done to me according to your word' — is the pivotal moment of salvation history. This feast is exactly nine months before Christmas.",
  },
  "04-23": {
    name: "St. George",
    feastDay: "04-23",
    bornDied: "d. 303",
    bio: "Roman soldier and martyr under Diocletian. Though little is historically verified, his legendary dragon-slaying represents the triumph of good over evil, Christianity over paganism. One of the most venerated saints in both East and West.",
    patronOf: "England, soldiers, scouts, Georgia",
  },
  "04-29": {
    name: "St. Catherine of Siena",
    feastDay: "04-29",
    bornDied: "1347–1380",
    bio: "Doctor of the Church and co-patroness of Europe. A Dominican tertiary who never learned to read until miraculously taught. She boldly urged Pope Gregory XI to return the papacy from Avignon to Rome. Her Dialogue is a mystical masterpiece.",
    patronOf: "Europe, Italy, nurses, fire prevention",
  },
  "05-01": {
    name: "St. Joseph the Worker",
    feastDay: "05-01",
    bornDied: "1st century",
    bio: "Pope Pius XII instituted this feast in 1955 to honor St. Joseph as a model for all workers and to consecrate the dignity of human labor to God. Christ Himself was known as 'the carpenter's son.'",
    patronOf: "Workers, craftsmen",
  },
  "05-03": {
    name: "Sts. Philip & James",
    feastDay: "05-03",
    bornDied: "1st century",
    bio: "Two of the twelve Apostles. Philip was from Bethsaida and brought Nathanael to Jesus. James 'the Less' was the first Bishop of Jerusalem and author of the Letter of James. Both were martyred for their faith.",
  },
  "05-14": {
    name: "St. Matthias",
    feastDay: "05-14",
    bornDied: "1st century",
    bio: "Chosen by lot to replace Judas Iscariot among the Twelve (Acts 1:15-26). He had been a witness of Jesus's entire ministry. He preached in Judaea and Ethiopia and was martyred, likely by axe.",
    patronOf: "Alcoholics, carpenters, tailors",
  },
  "05-26": {
    name: "St. Philip Neri",
    feastDay: "05-26",
    bornDied: "1515–1595",
    bio: "The 'Apostle of Rome' and founder of the Oratorians. Known for his joyful, unconventional approach to holiness — he welcomed everyone, used humor in spiritual direction, and reportedly levitated during Mass. Called the 'Second Apostle of Rome.'",
    patronOf: "Rome, joy, humor",
  },
  "05-31": {
    name: "The Visitation of Mary",
    feastDay: "05-31",
    bornDied: "–",
    bio: "Mary visits her cousin Elizabeth, who is pregnant with John the Baptist. At Mary's greeting, the child leaps in Elizabeth's womb and she is filled with the Holy Spirit, exclaiming: 'Blessed are you among women!' Mary then proclaims the Magnificat.",
  },
  "06-13": {
    name: "St. Anthony of Padua",
    feastDay: "06-13",
    bornDied: "1195–1231",
    bio: "Franciscan friar and Doctor of the Church. One of the most beloved saints, known for powerful preaching and miraculous gifts. Named a Doctor of the Church just one year after his death — the quickest in history.",
    patronOf: "Lost things, the poor, travelers, Portugal, Brazil",
  },
  "06-21": {
    name: "St. Aloysius Gonzaga",
    feastDay: "06-21",
    bornDied: "1568–1591",
    bio: "Renounced his noble title to become a Jesuit. He died at 23 while nursing plague victims in Rome. His purity, prayer life, and self-denial made him a model for young people.",
    patronOf: "Youth, students, Jesuit scholastics",
  },
  "06-24": {
    name: "Birth of St. John the Baptist",
    feastDay: "06-24",
    bornDied: "~6 BC–~30 AD",
    bio: "One of only three birthdays celebrated in the Church's calendar (along with Jesus and Mary). The forerunner of Christ who 'prepared the way of the Lord.' Jesus declared: 'Among those born of women there has arisen no one greater than John the Baptist.'",
    patronOf: "Baptism, converts, Jordan",
  },
  "06-29": {
    name: "Sts. Peter & Paul",
    feastDay: "06-29",
    bornDied: "d. ~64–67",
    bio: "This Solemnity honors the two great pillars of the Roman Church. Peter, the first Pope, was crucified upside down. Paul, the Apostle to the Gentiles, was beheaded. Together their martyrdom in Rome established it as the center of Christianity.",
    patronOf: "Rome, papacy, missions",
  },
  "07-03": {
    name: "St. Thomas the Apostle",
    feastDay: "07-03",
    bornDied: "1st century",
    bio: "Apostle whose doubt gave way to profound faith — 'My Lord and my God!' He is traditionally credited with evangelizing India, where the Thomas Christians trace their origin to him. Martyred by a spear in India.",
    patronOf: "India, architects, blind people, doubt",
  },
  "07-11": {
    name: "St. Benedict of Nursia",
    feastDay: "07-11",
    bornDied: "480–547",
    bio: "Father of Western monasticism and patron of Europe. His Rule of St. Benedict has guided monastic communities for 1,500 years, balancing prayer and work (ora et labora). His twin sister was St. Scholastica.",
    patronOf: "Europe, monks, students, against evil",
  },
  "07-22": {
    name: "St. Mary Magdalene",
    feastDay: "07-22",
    bornDied: "1st century",
    bio: "The 'Apostle to the Apostles' — the first witness of the Resurrection. She stood at the foot of the Cross and was the first to see the Risen Christ. Pope Francis elevated her memorial to a feast in 2016, recognizing her unique role.",
    patronOf: "Women, repentant sinners, pharmacists, hairdressers",
  },
  "07-25": {
    name: "St. James the Apostle",
    feastDay: "07-25",
    bornDied: "d. 44",
    bio: "Son of Zebedee and brother of John. One of the inner circle with Peter and John, present at the Transfiguration and Gethsemane. The first apostle to be martyred — beheaded by Herod Agrippa I (Acts 12). His shrine at Santiago de Compostela is one of the greatest pilgrimage sites.",
    patronOf: "Spain, pilgrims, laborers",
  },
  "07-26": {
    name: "Sts. Joachim & Anne",
    feastDay: "07-26",
    bornDied: "1st century BC",
    bio: "The parents of the Blessed Virgin Mary and grandparents of Jesus — 'the grandparents of God.' Though not mentioned in Scripture, ancient tradition honors them as the holy couple who raised Mary. Devotion to Anne has been continuous since the 6th century.",
    patronOf: "Grandparents, mothers, Canada, Brittany",
  },
  "07-29": {
    name: "St. Martha",
    feastDay: "07-29",
    bornDied: "1st century",
    bio: "Sister of Mary and Lazarus, close friends of Jesus. She is known for both her service ('Martha, Martha, you are anxious about many things') and her profound faith: 'I believe that you are the Christ, the Son of God.' Both service and contemplation belong in Christian life.",
    patronOf: "Cooks, servants, homemakers, hotels",
  },
  "08-04": {
    name: "St. John Vianney",
    feastDay: "08-04",
    bornDied: "1786–1859",
    bio: "The Curé d'Ars, patron of parish priests. Though he struggled academically, he became one of the most celebrated confessors in history. He spent up to 18 hours a day in the confessional, and thousands traveled to Ars to confess to him.",
    patronOf: "Parish priests, confessors",
  },
  "08-08": {
    name: "St. Dominic",
    feastDay: "08-08",
    bornDied: "1170–1221",
    bio: "Founded the Order of Preachers (Dominicans) to combat heresy through preaching and learning. He is associated with the Rosary and embodied poverty, penance, and prayer. His order produced Thomas Aquinas and Albert the Great.",
    patronOf: "Astronomers, preachers, the Dominican Republic",
  },
  "08-10": {
    name: "St. Lawrence",
    feastDay: "08-10",
    bornDied: "d. 258",
    bio: "Deacon of Rome martyred on a gridiron. When ordered to hand over the Church's treasures, he presented the poor and sick, saying 'These are the treasures of the Church.' One of the most venerated martyrs of Rome, he reportedly said while being grilled: 'Turn me over, I'm done on this side.'",
    patronOf: "Cooks, comedians, librarians, the poor",
  },
  "08-11": {
    name: "St. Clare of Assisi",
    feastDay: "08-11",
    bornDied: "1194–1253",
    bio: "Founded the Order of Poor Ladies (Poor Clares) after being inspired by St. Francis. She lived a life of radical poverty, contemplation, and joy for 42 years. When too ill to attend Mass, she reportedly saw it miraculously projected on her cell wall — hence patroness of television.",
    patronOf: "Television, eye disease, embroiderers",
  },
  "08-15": {
    name: "Assumption of Mary",
    feastDay: "08-15",
    bornDied: "–",
    bio: "This Solemnity celebrates the dogma defined by Pope Pius XII in 1950: that Mary, at the end of her earthly life, was taken up body and soul into heavenly glory. The Assumption is the foretaste and pledge of what awaits all the faithful in Christ.",
    patronOf: "A Holy Day of Obligation",
  },
  "08-20": {
    name: "St. Bernard of Clairvaux",
    feastDay: "08-20",
    bornDied: "1090–1153",
    bio: "Doctor of the Church and reformer of the Cistercians. His preaching launched the Second Crusade and he influenced the election of popes. His mystical theology on love of God and devotion to Mary remains deeply influential.",
    patronOf: "Beekeepers, candle makers, Gibraltar",
  },
  "08-22": {
    name: "Queenship of Mary",
    feastDay: "08-22",
    bornDied: "–",
    bio: "One week after the Assumption, the Church celebrates Mary's Queenship over all creation. Pope Pius XII instituted this feast in 1954 to close the Marian Year. As Mother of the King of Kings, Mary shares in Christ's royal dignity.",
    patronOf: "Queens, the heavenly court",
  },
  "08-24": {
    name: "St. Bartholomew",
    feastDay: "08-24",
    bornDied: "1st century",
    bio: "Apostle identified with Nathanael in John's Gospel, who received Christ's famous tribute: 'Here is a true Israelite in whom there is no guile.' He preached in India and Armenia and was martyred by being flayed alive.",
    patronOf: "Armenia, tanners, leather workers, plasterers",
  },
  "08-27": {
    name: "St. Monica",
    feastDay: "08-27",
    bornDied: "331–387",
    bio: "Mother of St. Augustine. For seventeen years she prayed and wept for her wayward son's conversion. Her perseverance in prayer is a model for all parents. St. Ambrose told her: 'The child of those tears shall never perish.'",
    patronOf: "Mothers, wives, abuse victims, alcoholics",
  },
  "08-28": {
    name: "St. Augustine of Hippo",
    feastDay: "08-28",
    bornDied: "354–430",
    bio: "Doctor of the Church and Bishop of Hippo. His Confessions — 'Our heart is restless until it rests in Thee, O Lord' — is the most widely read autobiography in history. His City of God and On the Trinity shaped Western Christianity profoundly.",
    patronOf: "Theologians, brewers, printers, eyes",
  },
  "09-03": {
    name: "St. Gregory the Great",
    feastDay: "09-03",
    bornDied: "540–604",
    bio: "One of only two popes called 'the Great,' and a Doctor of the Church. He reformed the liturgy (Gregorian Chant is named after him), sent missionaries to England, and wrote extensively on Scripture and pastoral theology.",
    patronOf: "Popes, teachers, musicians, England",
  },
  "09-08": {
    name: "Birth of the Blessed Virgin Mary",
    feastDay: "09-08",
    bornDied: "–",
    bio: "The Church celebrates the birthday of Our Lady — the dawn before the sunrise of Christ. Exactly nine months after the feast of the Immaculate Conception, this feast reminds us that Mary's birth brought new hope to a fallen world.",
  },
  "09-13": {
    name: "St. John Chrysostom",
    feastDay: "09-13",
    bornDied: "347–407",
    bio: "Archbishop of Constantinople and Doctor of the Church. His surname means 'golden-mouthed' in Greek — he was the greatest preacher of the ancient Church. His homilies on Scripture and his Divine Liturgy are still in use today in Eastern Christianity.",
    patronOf: "Preachers, orators, education",
  },
  "09-14": {
    name: "Exaltation of the Holy Cross",
    feastDay: "09-14",
    bornDied: "–",
    bio: "This feast celebrates the discovery of the True Cross by St. Helena in 326 and its later recovery from Persian hands in 628. The Cross, once an instrument of shame, has become the great sign of victory. 'We adore Your Cross, O Lord.'",
  },
  "09-15": {
    name: "Our Lady of Sorrows",
    feastDay: "09-15",
    bornDied: "–",
    bio: "The day after the Exaltation of the Cross, the Church contemplates Mary standing at the foot of the Cross. The seven sorrows of Mary (the prophecy of Simeon, the flight to Egypt, the loss of Jesus, meeting on the Way of the Cross, the Crucifixion, the Descent, and the Burial) are meditated upon.",
    patronOf: "Slovakia, mothers in grief",
  },
  "09-16": {
    name: "Sts. Cornelius & Cyprian",
    feastDay: "09-16",
    bornDied: "d. 253 / d. 258",
    bio: "Cornelius was Pope and Cyprian Bishop of Carthage. Both suffered during the Decian persecution and grappled with the question of how to receive back those who had lapsed during persecution. Both were eventually martyred.",
  },
  "09-21": {
    name: "St. Matthew",
    feastDay: "09-21",
    bornDied: "1st century",
    bio: "Tax collector called by Jesus to be one of the Twelve. Author of the first Gospel. His conversion from an occupation despised by Jews to Apostle and Evangelist shows the radical power of Christ's call.",
    patronOf: "Tax collectors, accountants, bankers, security guards",
  },
  "09-27": {
    name: "St. Vincent de Paul",
    feastDay: "09-27",
    bornDied: "1581–1660",
    bio: "Patron of charitable works and founder of the Vincentians and the Daughters of Charity. He organized relief for galley slaves, the rural poor, orphans, the elderly, and the sick in Paris. He transformed French Catholicism's approach to the poor.",
    patronOf: "Charities, volunteers, Madagascar, horses",
  },
  "09-29": {
    name: "Sts. Michael, Gabriel & Raphael",
    feastDay: "09-29",
    bornDied: "–",
    bio: "This feast honors the three archangels named in Scripture. Michael, the warrior archangel who fights Satan (Revelation 12); Gabriel, the messenger who announced the Incarnation to Mary (Luke 1); and Raphael, the healer who accompanied Tobias (Tobit 12).",
    patronOf:
      "Michael: warriors, police, paratroopers; Gabriel: communications; Raphael: travelers, healers",
  },
  "09-30": {
    name: "St. Jerome",
    feastDay: "09-30",
    bornDied: "347–420",
    bio: "Doctor of the Church and greatest Scripture scholar of antiquity. He translated the entire Bible from Hebrew and Greek into Latin — the Vulgate — which remained the standard text for over a thousand years. 'Ignorance of Scripture is ignorance of Christ.'",
    patronOf: "Scripture scholars, librarians, translators",
  },
  "10-01": {
    name: "St. Thérèse of the Child Jesus",
    feastDay: "10-01",
    bornDied: "1873–1897",
    bio: "The 'Little Flower' and Doctor of the Church. She died of tuberculosis at 24 having never left her Carmelite convent, yet became one of the most popular saints in history. Her 'little way' — doing small things with great love — is her spiritual legacy.",
    patronOf: "Missions, France, Russia, AIDS patients, florists",
  },
  "10-02": {
    name: "Guardian Angels",
    feastDay: "10-02",
    bornDied: "–",
    bio: "The Church celebrates the Guardian Angels — the personal angels assigned to watch over every human soul. Jesus said: 'See that you do not despise one of these little ones. For I tell you that in heaven their angels always see the face of my Father' (Matthew 18:10).",
  },
  "10-04": {
    name: "St. Francis of Assisi",
    feastDay: "10-04",
    bornDied: "1181–1226",
    bio: "One of the most beloved saints in history. Son of a wealthy merchant who chose radical poverty after a conversion experience. He founded the Franciscans, received the stigmata, and composed the 'Canticle of the Sun.' His simplicity, joy, and love of creation transformed the Church.",
    patronOf: "Animals, ecology, Italy, merchants, peace",
  },
  "10-07": {
    name: "Our Lady of the Rosary",
    feastDay: "10-07",
    bornDied: "–",
    bio: "Instituted by Pope Pius V to commemorate the Christian victory at the Battle of Lepanto in 1571, attributed to Mary's intercession through the Rosary. The Rosary is the great prayer of the Church for peace and the contemplation of Christ's mysteries.",
  },
  "10-15": {
    name: "St. Teresa of Ávila",
    feastDay: "10-15",
    bornDied: "1515–1582",
    bio: "First woman Doctor of the Church (with Catherine of Siena). She reformed the Carmelite Order and wrote masterpieces of mystical theology: The Way of Perfection and The Interior Castle. Her friendship with St. John of the Cross deepened the Carmelite tradition.",
    patronOf: "Spain, headache sufferers, lace makers",
  },
  "10-17": {
    name: "St. Ignatius of Antioch",
    feastDay: "10-17",
    bornDied: "d. ~108",
    bio: "Third Bishop of Antioch and one of the Apostolic Fathers. On his way to martyrdom in Rome, he wrote seven letters that are invaluable for understanding the early Church. He coined the term 'Catholic Church' — the first known use of the word.",
    patronOf: "Throat diseases, churches in the Near East",
  },
  "10-18": {
    name: "St. Luke",
    feastDay: "10-18",
    bornDied: "1st century",
    bio: "Author of the third Gospel and the Acts of the Apostles — together comprising over a quarter of the New Testament. A physician and companion of St. Paul. His Gospel is the most literary and emphasizes mercy, prayer, and the Holy Spirit.",
    patronOf: "Physicians, surgeons, artists, painters",
  },
  "10-28": {
    name: "Sts. Simon & Jude",
    feastDay: "10-28",
    bornDied: "1st century",
    bio: "Two of the twelve Apostles. Simon was called 'the Zealot' (perhaps a former political revolutionary). Jude (Thaddaeus) is the author of the Letter of Jude and is the patron of desperate causes — invoked when all else fails.",
    patronOf: "Jude: hopeless and desperate causes; Simon: woodcutters",
  },
  "11-01": {
    name: "All Saints",
    feastDay: "11-01",
    bornDied: "–",
    bio: "A Holy Day of Obligation honoring all the saints — known and unknown — who now enjoy the beatific vision in Heaven. This feast reminds us that holiness is universal and that we are all called to become saints. The saints are our friends and intercessors.",
    patronOf: "A Holy Day of Obligation",
  },
  "11-02": {
    name: "All Souls",
    feastDay: "11-02",
    bornDied: "–",
    bio: "The Church's solemn commemoration of all the faithful departed — those undergoing purification in Purgatory. We pray for the dead, trusting in God's mercy and the doctrine of the Communion of Saints. Visiting a cemetery and gaining indulgences for the dead is a beautiful tradition.",
  },
  "11-04": {
    name: "St. Charles Borromeo",
    feastDay: "11-04",
    bornDied: "1538–1584",
    bio: "Cardinal Archbishop of Milan and one of the key figures of the Counter-Reformation. He implemented the decrees of the Council of Trent and established seminaries, Sunday schools, and parishes. He personally served plague victims in Milan.",
    patronOf: "Bishops, seminarians, apple orchards, against ulcers",
  },
  "11-09": {
    name: "Dedication of the Lateran Basilica",
    feastDay: "11-09",
    bornDied: "–",
    bio: "The Lateran Basilica in Rome is the cathedral of the Bishop of Rome — the Pope — and is therefore 'the mother of all churches.' This feast celebrates its dedication and reminds us of the unity of the universal Church under the Pope.",
  },
  "11-11": {
    name: "St. Martin of Tours",
    feastDay: "11-11",
    bornDied: "316–397",
    bio: "Bishop of Tours and one of the most popular saints of the Middle Ages. As a soldier, he cut his cloak in half to share with a freezing beggar — and that night dreamed of Christ wearing it. He became a monk, then bishop, and a model of pastoral charity.",
    patronOf: "France, soldiers, beggars, geese, winemakers",
  },
  "11-13": {
    name: "St. Frances Xavier Cabrini",
    feastDay: "11-13",
    bornDied: "1850–1917",
    bio: "First American citizen to be canonized. An Italian immigrant, she founded the Missionary Sisters of the Sacred Heart and established hospitals, schools, and orphanages across the United States and Latin America.",
    patronOf: "Immigrants, hospital administrators, United States",
  },
  "11-17": {
    name: "St. Elizabeth of Hungary",
    feastDay: "11-17",
    bornDied: "1207–1231",
    bio: "Princess of Hungary who gave away her wealth to feed the poor and founded a hospital. After her husband's death, she was expelled from court by her in-laws. She died at 24 after years of intense asceticism and charity.",
    patronOf: "The poor, bakers, hospitals, tertiaries",
  },
  "11-21": {
    name: "Presentation of Mary",
    feastDay: "11-21",
    bornDied: "–",
    bio: "Based on ancient tradition, this feast commemorates Mary being presented in the Temple at age three by her parents Joachim and Anne, consecrating her to God. The Eastern Church has celebrated this feast since the 6th century.",
  },
  "11-22": {
    name: "St. Cecilia",
    feastDay: "11-22",
    bornDied: "d. ~230",
    bio: "Roman virgin and martyr who consecrated her virginity to God. According to tradition, she sang hymns to God on her wedding day. She was condemned to death by suffocation and then beheaded. One of the seven women named in the Roman Canon.",
    patronOf: "Musicians, composers, organ builders, singers, poets",
  },
  "11-30": {
    name: "St. Andrew",
    feastDay: "11-30",
    bornDied: "d. ~60",
    bio: "The first called of the Apostles — he brought his brother Peter to Jesus (John 1:41). He was crucified on an X-shaped cross (Saltire) and reportedly said: 'O good Cross, made beautiful by the body of the Lord, long desired, ardently loved.'",
    patronOf: "Scotland, Russia, Greece, Ukraine, fishermen",
  },
  "12-03": {
    name: "St. Francis Xavier",
    feastDay: "12-03",
    bornDied: "1506–1552",
    bio: "Co-founder of the Jesuits and greatest missionary since St. Paul. He baptized tens of thousands in India, Japan, and the Far East. He died on the island of Sancian while trying to enter China. Patron of all foreign missions.",
    patronOf: "Missions, foreign missions, Japan, India, Navarre",
  },
  "12-06": {
    name: "St. Nicholas of Myra",
    feastDay: "12-06",
    bornDied: "270–343",
    bio: "Bishop of Myra in Asia Minor (modern Turkey), famous for his extraordinary generosity. He secretly provided dowries for three poor girls, gave gifts to children, and was present at the Council of Nicaea. The origin of Santa Claus.",
    patronOf: "Children, sailors, merchants, bakers, Russia, Greece",
  },
  "12-07": {
    name: "St. Ambrose",
    feastDay: "12-07",
    bornDied: "340–397",
    bio: "Archbishop of Milan and Doctor of the Church. Elected bishop by popular acclaim before even being baptized. He baptized St. Augustine, stood up to Emperor Theodosius, and developed the Western liturgical tradition. His hymns are still sung today.",
    patronOf: "Bishops, beekeepers, candlemakers, France, Milan",
  },
  "12-08": {
    name: "Immaculate Conception of Mary",
    feastDay: "12-08",
    bornDied: "–",
    bio: "This Solemnity celebrates the dogma defined by Pope Pius IX in 1854: that Mary was preserved from original sin from the very moment of her conception, by a singular grace of God in view of the merits of Jesus Christ. A Holy Day of Obligation.",
    patronOf: "A Holy Day of Obligation, United States",
  },
  "12-09": {
    name: "St. Juan Diego",
    feastDay: "12-09",
    bornDied: "1474–1548",
    bio: "Aztec convert to whom Our Lady of Guadalupe appeared in 1531 on Tepeyac hill near Mexico City. He carried the miraculous image of Our Lady imprinted on his tilma (cloak), which is still preserved and venerated in the Basilica of Guadalupe.",
    patronOf: "Indigenous peoples of the Americas",
  },
  "12-12": {
    name: "Our Lady of Guadalupe",
    feastDay: "12-12",
    bornDied: "–",
    bio: "On this date in 1531, Mary appeared to St. Juan Diego in Mexico, leaving her miraculous image on his tilma. This apparition led to the conversion of millions of indigenous people in the Americas. The Basilica of Guadalupe in Mexico City is the most visited Marian shrine in the world.",
    patronOf: "Americas, Mexico, unborn children, Philippines",
  },
  "12-13": {
    name: "St. Lucy",
    feastDay: "12-13",
    bornDied: "283–304",
    bio: "Sicilian virgin and martyr under Diocletian. Her name means 'light.' She consecrated her virginity to Christ and distributed her dowry to the poor. She was stabbed in the throat after surviving attempts to burn her. Patron of the blind.",
    patronOf: "The blind, eye diseases, Sweden, Syracuse",
  },
  "12-14": {
    name: "St. John of the Cross",
    feastDay: "12-14",
    bornDied: "1542–1591",
    bio: "Doctor of the Church and co-reformer of the Carmelites with St. Teresa of Ávila. He was imprisoned by his own friars for reform efforts. In a tiny cell he wrote some of the greatest mystical poetry in any language: The Dark Night of the Soul, The Spiritual Canticle.",
    patronOf: "Mystics, contemplatives, Spanish poets",
  },
  "12-25": {
    name: "The Nativity of Our Lord",
    feastDay: "12-25",
    bornDied: "–",
    bio: "Christmas — the Solemnity of the Nativity of Jesus Christ, the Son of God made flesh. 'The Word was made flesh and dwelt among us' (John 1:14). A Holy Day of Obligation. The great 'yes' of God to humanity, born in a manger in Bethlehem.",
    patronOf: "A Holy Day of Obligation",
  },
  "12-26": {
    name: "St. Stephen",
    feastDay: "12-26",
    bornDied: "d. ~34",
    bio: "First Christian martyr. One of the first seven deacons, he was stoned to death after a powerful speech to the Sanhedrin (Acts 6-7). As he died, he saw 'the heavens opened and the Son of Man standing at the right hand of God' and prayed for his persecutors — including the young Saul of Tarsus.",
    patronOf: "Deacons, stonemasons, bricklayers, casket makers",
  },
  "12-27": {
    name: "St. John the Apostle",
    feastDay: "12-27",
    bornDied: "6–100",
    bio: "The 'Beloved Disciple' — the only apostle who did not flee at the Crucifixion. He cared for Mary until her death. Author of the fourth Gospel, three epistles, and Revelation. He lived to extreme old age in Ephesus, reportedly saying only: 'Little children, love one another.'",
    patronOf: "Love, loyalty, friendship, authors, Asia Minor",
  },
  "12-28": {
    name: "Holy Innocents",
    feastDay: "12-28",
    bornDied: "d. ~1 AD",
    bio: "The male infants massacred by Herod in his attempt to kill the newborn King (Matthew 2:16-18). They died for Christ without knowing Him. The Church venerates them as the first martyrs — witnesses by their death to the One who had come to save all humanity.",
    patronOf: "Babies, foundlings, innocents",
  },
  "12-29": {
    name: "St. Thomas Becket",
    feastDay: "12-29",
    bornDied: "1118–1170",
    bio: "Archbishop of Canterbury martyred in his own cathedral by knights of King Henry II after defending the Church's rights against royal interference. He declared: 'I am ready to die for my Lord.' His shrine became the most visited pilgrimage site in England.",
    patronOf: "Clergy, secular clergy, England",
  },
};

export function getSaintOfDay(date: Date = new Date()): Saint {
  const mm = String(date.getMonth() + 1).padStart(2, "0");
  const dd = String(date.getDate()).padStart(2, "0");
  const key = `${mm}-${dd}`;
  return (
    SAINTS[key] ?? {
      name: "A Holy Saint",
      feastDay: key,
      bio: "The Church honors many saints whose stories have been passed down through centuries of faith. Today, pray for the intercession of all the saints in Heaven.",
    }
  );
}

export { SAINTS };

